{{- if .Values.namespace.create | default true }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: joke-platform
    app.kubernetes.io/part-of: joke-platform
{{- end }}
