apiVersion: v1
kind: Service
metadata:
  labels:
    app: ben-coeppicus
  name: ben-coeppicus
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ben-coeppicus
  type: NodePort